# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  version: '1.0.0-$(build.buildNumber)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: -c $(buildConfiguration)
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'PatrITech.WeChat.Work.Tests.settings.json'
- script: cp $(Agent.TempDirectory)/PatrITech.WeChat.Work.Tests.settings.json tests/PatrITech.WeChat.Work.Tests/bin/Release/netcoreapp2.2/settings.json -f
  displayName: Copy Settings File
- task: DotNetCoreCLI@2
  displayName: "Test"
  enabled: 'true'
  inputs:
    command: 'test'
    arguments: -c $(buildConfiguration) --logger trx --collect "Code coverage"
    nobuild: true
    projects: 'tests/**/*.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  displayName: "Package"
  enabled: 'true'
  inputs:
    command: 'pack'
    arguments: -c $(buildConfiguration)
    nobuild: true
    packagesToPack: 'src/*/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    versionEnvVar: version
    versioningScheme: 'byEnvVar'
    verbosityPack: Minimal
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'PatrITech.WeChat'
    publishLocation: 'Container'
