# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: -c $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    nobuild: true
    projects: 'tests/**/*.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  displayName: "Package"
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: 'src/**/*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    verbosityPack: 'Normal'
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'PatrITech.WeChat'
    publishLocation: 'Container'
